# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 56dbe2bf222a25bc74ae3ac3641f200f4b316ff555403f2125e9683254369cba9dbaaa965ae1c7c5ee8e17d289537f20c3076304e754ae19ae1a23a25060f841

test:
  secret_key_base: 973beb81853b7fadb10826ac7fe7732d5155a6a3becea97de5ae90ff521ee9b120edac50d51bdece74ab9c2abbb98e0f688d6c15796842ed23cb4ab09a8b97ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
