Family.create(family_name: "Gerard", password: "1")
Person.create(first_name: "Celeste", last_name: "Gerard", username: "Celeste", password: "1", family_id: 1, bio: "I love cookies.", image_url: "/assets/pa_1.jpg", dob: Date.new(1993,1,22), is_account: true )
Person.create(first_name: "John", last_name: "Neff", username: "JohnNeff", password: "1", family_id: 1, bio: "I attribute my success to this: I never gave or took any excuse.", image_url: "/assets/pa_1.jpg", dob: Date.new(1876,4,28), dod: Date.new(1957,1,1))
Person.create(first_name: "Carol", last_name: "Neff", username: "CarolNeff", password: "1", family_id: 1, bio: "Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.", image_url: "/assets/pa_1.jpg", dob: Date.new(1882,1,9), dod: Date.new(1877,1,10))
Person.create(first_name: "Stanley", last_name: "Neff", username: "StanleyNeff", password: "1", family_id: 1, bio: "I have learned over the years that when one's mind is made up, this diminishes fear.", image_url: "/assets/pa_1.jpg", dob: Date.new(1877,10,28), dod: Date.new(1967,11,7))
Person.create(first_name: "Thomas", last_name: "Neff", username: "ThomasNeff", password: "1", family_id: 1, bio: "I attribute my success to this: I never gave or took any excuse.", image_url: "/assets/pa_1.jpg", dob: Date.new(1882,9,13), dod: Date.new(1968,12,7))
Person.create(first_name: "Elwood", last_name: "Neff", username: "ElwoodNeff", password: "1", family_id: 1, bio: " The best time to plant a tree was 20 years ago. The second best time is now.", image_url: "/assets/pa_1.jpg", dob: Date.new(2000,1,1), dod: Date.new(1971,3,25))
Person.create(first_name: "John", last_name: "Burt", username: "JohnBurt", password: "1", family_id: 1, bio: "The only way to do great work is to love what you do.", image_url: "/assets/pa_1.jpg", dob: Date.new(1882,1,9), dod: Date.new(1968,12,7))
Person.create(first_name: "Geneve", last_name: "Burt", username: "GeneveBurt", password: "1", family_id: 1, bio: " Strive not to be a success, but rather to be of value.", image_url: "/assets/pa_1.jpg", dob: Date.new(1889,5,15), dod: Date.new(1971,3,25))
Person.create(first_name: "Karleen", last_name: "Burt", username: "KarleenBurt", password: "1", family_id: 1, bio: "Whatever the mind of man can conceive and believe, it can achieve.", image_url: "/assets/pa_1.jpg", dob: Date.new(1891,4,3), dod: Date.new(1974,12,4))
Person.create(first_name: "Bonnie", last_name: "Burt", username: "BonnieBurt", password: "1", family_id: 1, bio: "We become what we think about.", image_url: "/assets/pa_1.jpg", dob: Date.new(1901,4,28), dod: Date.new(1976,3,27))
Person.create(first_name: "John", last_name: "Burt", username: "JohnBurt", password: "1", family_id: 1, bio: "Too many of us are not living our dreams because we are living our fears.", image_url: "/assets/pa_1.jpg", dob: Date.new(1911,12,1), dod: Date.new(1978,11,23))
Person.create(first_name: "Lorele", last_name: "Burt", username: "LoreleBurt", password: "1", family_id: 1, bio: " The best time to plant a tree was 20 years ago. The second best time is now.", image_url: "/assets/pa_1.jpg", dob: Date.new(1912,12,14), dod: Date.new(1979,6,3))
Person.create(first_name: "George", last_name: "Graehl", username: "GeorgeGraehl", password: "1", family_id: 1, bio: "It is during our darkest moments that we must focus to see the light.", image_url: "/assets/pa_1.jpg", dob: Date.new(1919,10,8), dod: Date.new(1983,2,16))
Person.create(first_name: "Adah", last_name: "Graehl", username: "AdahGraehl", password: "1", family_id: 1, bio: "A person who never made a mistake never tried anything new.", image_url: "/assets/pa_1.jpg", dob: Date.new(1928,9,11), dod: Date.new(1986,4,9))
Person.create(first_name: "Ada", last_name: "Graehl", username: "AdaGraehl", password: "1", family_id: 1, bio: "We become what we think about.", image_url: "", dob: Date.new(1931,1,24), dod: Date.new(1991,5,26))
Person.create(first_name: "Ada", last_name: "Graehl", username: "AdaGraehl", password: "1", family_id: 1, bio: "I attribute my success to this: I never gave or took any excuse.", image_url: "/assets/pa_1.jpg", dob: Date.new(1949,10,9), dod: Date.new(1991,10,13))
Person.create(first_name: "Geneve", last_name: "Graehl", username: "GeneveGraehl", password: "1", family_id: 1, bio: "Life is 10% what happens to me and 90% of how I react to it.", image_url: "/assets/pa_1.jpg", dob: Date.new(1873,3,24), dod: Date.new(1991,10,13))
Person.create(first_name: "George", last_name: "Graehl", username: "GeorgeGraehl", password: "1", family_id: 1, bio: "The most common way people give up their power is by thinking they don't have any.", image_url: "/assets/pa_1.jpg", dob: Date.new(1874,7,23), dod: Date.new(1993,10,22))
Person.create(first_name: "Florence", last_name: "Graehl", username: "FlorenceGraehl", password: "1", family_id: 1, bio: " The best time to plant a tree was 20 years ago. The second best time is now.", image_url: "/assets/pa_1.jpg", dob: Date.new(1884,11,24), dod: Date.new(1996,8,22))
Person.create(first_name: "Adele", last_name: "Graehl", username: "AdeleGraehl", password: "1", family_id: 1, bio: "I attribute my success to this: I never gave or took any excuse.", image_url: "/assets/pa_1.jpg", dob: Date.new(1887,4,8), dod: Date.new(1999,2,8))
Person.create(first_name: "Helen", last_name: "Burt", username: "HelenBurt", password: "1", family_id: 1, bio: "Don't judge each day by the harvest you reap but by the seeds that you plant.", image_url: "/assets/pa_1.jpg", dob: Date.new(1887,9,28), dod: Date.new(2002,10,10))
Person.create(first_name: "Leland", last_name: "Burt", username: "LelandBurt", password: "1", family_id: 1, bio: "Do or do not. There is no try.", image_url: "/assets/pa_1.jpg", dob: Date.new(1892,7,18), dod: Date.new(2002,10,10))


Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_1.jpg", description: "Baby", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_2.jpg", description: "Car Couple", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_3.jpg", description: "Cat Lady", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_4.jpg", description: "Home on the Range", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_6.jpg", description: "Campfire", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_8.jpg", description: "Couple", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_12.jpg", description: "River", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_13.jpg", description: "Donkey", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_14.jpg", description: "Macro Girl", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_19.jpg", description: "Bench", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_20.jpg", description: "Necktie", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_22.jpg", description: "Book", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_25.jpg", description: "MacroBoy", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_28.jpg", description: "Chair Man", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_29.jpg", description: "Dad Daughter", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_34.jpg", description: "Friends", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_36.jpg", description: "Twins", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_38.jpg", description: "Portrait Woman", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_39.jpg", description: "Boys", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_40.jpg", description: "Portrait Man", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_42.jpg", description: "Lorele Young", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_43.jpg", description: "House White", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_44.jpg", description: "House Dark", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_45.jpg", description: "Wedding Gramp", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_46.jpg", description: "Wedding Bob", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_47.jpg", description: "Coat", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_48.jpg", description: "Eve", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_49.jpg", description: "Grandpa", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_50.jpeg", description: "Band", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_52.jpg", description: "Little One", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_53.jpg", description: "Twins", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_54.jpg", description: "Friends", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_55.jpg", description: "TwinsBike", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_57.jpg", description: "Lawn Chair Radio", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_58.jpg", description: "Funeral", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_59.jpg", description: "Car Family", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_60.jpg", description: "Baby Coat", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_61.jpg", description: "Park Happy", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_62.jpg", description: "Grandpa Portrait", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_63.jpg", description: "Car Girls", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_64.jpg", description: "Grandma Grandpa Boy", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_65.jpg", description: "Cowboy", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_67.jpg", description: "Schoolyard", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_68.jpg", description: "Girls Outside", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_70.jpg", description: "Grandma", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_72.jpg", description: "Mountain Couple", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_73.jpg", description: "Portrait Ada", family_id: 1)
Memory.create(title: Faker::Lorem.sentence, image_url:"/assets/pa_74.jpg", description: "Engineering", family_id: 1)
