Person.create(first_name: "Eric", last_name: "Kim", username: "Eric", password: "1", family_id: 7, bio: "Test", image_url: "", dob: Date.new(2000,1,1), dod: Date.new(2001,2,2), is_account: true)
Person.create(first_name: "Sandy", last_name: "Kim", username: "SandyKim", password: "1", family_id: 7, bio: "Test", image_url: "", dob: Date.new(2000,1,1), dod: Date.new(2001,2,2))
Person.create(first_name: "Celeste", last_name: "Kim", username: "CelesteKim", password: "1", family_id: 7, bio: "Test", image_url: "", dob: Date.new(2000,1,1), dod: Date.new(2001,2,2))
Person.create(first_name: "Harim", last_name: "Kim", username: "HarimKim", password: "1", family_id: 7, bio: "Test", image_url: "", dob: Date.new(2000,1,1), dod: Date.new(2001,2,2))
Person.create(first_name: "Kate", last_name: "Kim", username: "KateKim", password: "1", family_id: 7, bio: "Test", image_url: "", dob: Date.new(2000,1,1), dod: Date.new(2001,2,2))
Person.create(first_name: "Alice", last_name: "Kim", username: "AliceKim", password: "1", family_id: 7, bio: "Test", image_url: "", dob: Date.new(2000,1,1), dod: Date.new(2001,2,2))
Person.create(first_name: "Gary", last_name: "Kim", username: "GaryKim", password: "1", family_id: 7, bio: "Test", image_url: "", dob: Date.new(2000,1,1), dod: Date.new(2001,2,2))
